name: handy_extensions
description: Handy Extension is just a simple library with extensions to the core libraries to make them more handy and quicker to use.
version: 0.1.5+3
repository: https://github.com/iamngoni/handy_extensions

environment:
  sdk: ">=2.12.0 <= 3.5.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
