name: handy_extensions
description: Handy Extension is just a simple library with extensions to the core libraries to make them more handy and quicker to use.
version: 0.0.6+1
repository: https://github.com/iamngoni/handy_extensions

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  money_formatter: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: