name: Handy Extensions Coverage
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/coverage.svg"

jobs:
  coverage-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          file: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: iamngoni/handy_extensions